### ISSUE TITLE
FYI: domain breitbart.lol

### ISSUE THREAD

**Issue by adrn** [Data4Democracy/far-right-analysis#10]
I noticed a few days ago that http://breitbart.lol was available, so naturally I had to buy it...If anyone needs a place to host things, let me know!

**Comment by sjacks26** [comment]
haha nice! We should find something to put here. Gotta capitalize on that great url.

**Comment by bbrewington** [comment]
That should be the homepage of data products we produce in this project.  Would it violate their trademark?  Pretty hilarious, anyway :)

**Comment by gati** [comment]
@bbrewington that is an amazing idea. Also @adrn that's the best domain purchase I've seen in awhile. :)
