### ISSUE TITLE
Create Stormfront scraper

### ISSUE THREAD

**Issue by gati** [Data4Democracy/far-right-analysis#18]
Fair warning, Stormfront is a pretty gross corner of the Internet. But if you're up for it, this issue to write a scraper (see the Python `scrapy` library for getting started) to extract messages from Stormfront's forums and save them to a sqlite database, series of JSON files, series of CSVs, or whatever format is easiest for you.

**Comment by JasonLunn** [comment]
Is it important that the tool is python based? Would ruby be acceptable?

**Comment by gati** [comment]
Ruby is cool too - whatever you're comfortable writing in!

**Comment by JasonLunn** [comment]
Is there an S3/GDS store where you want the data stored?

**Comment by gati** [comment]
Yes! @bstarling (here and on Slack) can get you hooked up with credentials for pushing to our S3 bucket.

**Comment by alliesaizan** [comment]
Hello, I am new to Data for Democracy and would like to help out on this project. What is the current status of this project?

**Comment by bstarling** [comment]
Hey @alliesaizan thank you for your interest. We have actually completed this task (apologies for the stale GH issue!)

We are in a re-grouping phase right now as some of the project leads have had to move on to other obligations. We are looking for new ideas or project proposals in preparation for our global Hackathon on Sept 30th. Feel free to DM me on slack @bstarling & we can discuss (I see you're already in #far-right).
