### ISSUE TITLE
Scrape bbs.dailystormer.com

### ISSUE THREAD

**Issue by gati** [Data4Democracy/far-right-analysis#22]
Write a scraper (see the `scrapy` Python library as a good starting point) for the Daily Stormer bulletin boards. Fair warning: this content will be really offensive.

Once you have a scraper working, grab some sample data and throw it into a sqlite database, series of JSON files, CSV files, or whatever is easiest for you. We'll throw it up on data.world and start some exploratory analysis!

**Comment by samzhang111** [comment]
I have this already! I'll try to make it out to crystal city and maybe someone can help me upload it

**Comment by citizenrich** [comment]
Daily Stormer is now archived up to April 1.

**Comment by gati** [comment]
@citizenrich that's awesome! Thanks for tackling that. Is the data up on data.world, or the s3 bucket @bstarling has been managing (or somewhere else)?

**Comment by citizenrich** [comment]
Enjoy! It's in the s3 bucket under archive/stormer as "daily_stormer_17-04-01.sql". @bstarling

**Comment by bdlacree** [comment]
Hello! I'm curious if you can point me toward where to find this archive. I am new to the D4D project(s) but would be interested in the data. Thanks!

**Comment by samzhang111** [comment]
@bdlacree Want to ping me on the D4D slack? I am `@sam`
